-- 사용자 정보
-- 메뉴 마스터 (4자리 확장 구조)
CREATE TABLE `op_menu` (
  `MENU_ID` varchar(24) NOT NULL,
  `MENU_TY_CODE` varchar(4) NOT NULL COMMENT '10:카테고리, 20:메뉴, 30:기능',
  `MENU_LEVEL` int DEFAULT NULL,
  `MENU_NM` varchar(200) DEFAULT NULL,
  `URL` varchar(200) DEFAULT NULL,
  `SORT_ORDR` int DEFAULT NULL,
  `USE_YN` varchar(1) DEFAULT NULL,
  `SORT_ORDR_1` int DEFAULT NULL,
  `SORT_ORDR_2` int DEFAULT NULL,
  `SORT_ORDR_3` int DEFAULT NULL,
  `SORT_ORDR_4` int DEFAULT NULL,
  `SORT_ORDR_5` int DEFAULT NULL,
  `SORT_ORDR_6` int DEFAULT NULL,
  `REGISTER_NO` int DEFAULT NULL,
  `REGIST_DT` datetime DEFAULT NULL,
  `UPDUSR_NO` int DEFAULT NULL,
  `UPDT_DT` datetime DEFAULT NULL,
  PRIMARY KEY (`MENU_ID`)
);


-- 최상위 메뉴 추가
INSERT INTO op_menu (MENU_ID, MENU_TY_CODE, MENU_LEVEL, MENU_NM, SORT_ORDR, USE_YN, SORT_ORDR_1, REGIST_DT) 
VALUES ('1000', '10', 1, 'Home', 1, 'Y', 1, NOW());