1.설문
-- planfaidb.tb_survey definition
CREATE TABLE `tb_survey` (
  `SURVEY_SEQ` int NOT NULL AUTO_INCREMENT,
  `SURVEY_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `SURVEY_TITLE` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `OPENED` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `CLOSED` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `ADMINEMAIL` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `ADMINPID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `ACCESSRESULTSRESTRICTION` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `RESULTSPASSWORD` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `ENTRYRESTRICTION` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `ENTRYPASSWORD` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `MEMBERS` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `ONEENTRYONLY` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `SHOWBORDER` char(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `EXPORTDELIMITER` char(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `EXPORTINCLUDEQUESTIONS` char(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `IP` char(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `BROWSERID` char(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `BGCOLOR` varchar(7) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `TEXTCOLOR` varchar(7) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `FONT_SIZE` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `HEADER` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `FOOTER` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `BASEHREF` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `USERCSS` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `DIVIDER` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `EXITPAGETEXT_ISHTML` char(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `EXITPAGETEXT` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `NUMBERRODUCTIONTEXT` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `REGISTER_NO` int DEFAULT NULL COMMENT '등록자 번호',
  `REGIST_DT` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
  `UPDUSR_NO` int DEFAULT NULL COMMENT '수정자 번호',
  `UPDT_DT` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  PRIMARY KEY (`SURVEY_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- planfaidb.tb_section definition
CREATE TABLE `tb_section` (
  `SECTION_SEQ` int NOT NULL AUTO_INCREMENT,
  `SURVEY_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `SECTION_ID` int NOT NULL,
  `SECTION_TITLE` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `SECTION_HTMLTITLE` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `REGISTER_NO` int DEFAULT NULL COMMENT '등록자 번호',
  `REGIST_DT` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
  `UPDUSR_NO` int DEFAULT NULL COMMENT '수정자 번호',
  `UPDT_DT` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  PRIMARY KEY (`SURVEY_ID`,`SECTION_ID`),
  UNIQUE KEY `SECTION_SEQ_UNIQUE` (`SECTION_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- planfaidb.tb_question definition

CREATE TABLE `tb_question` (
  `QUESTION_SEQ` int NOT NULL AUTO_INCREMENT,
  `SURVEY_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `SECTION_ID` int NOT NULL,
  `QUESTION_ID` int NOT NULL,
  `QUESTION_TYPE` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `SHOWDIVIDER` char(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `EXPORTINCLUDE` char(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `EXPORTEXPAND` char(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `QUESTIONTEXT` varchar(1000) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `QUESTION_CD` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `QUESTION_ISHTML` char(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `QUESTION_LAYOUT` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `QUESTION_LABEL` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `OTHERANSWER` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `TEXTCOLS` int DEFAULT NULL,
  `TEXTROWS` int DEFAULT NULL,
  `TEXTSIZE` int DEFAULT NULL,
  `MAXLENGTH` int DEFAULT NULL,
  `SUMMARY_CD` varchar(2) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT '0',
  `REGISTER_NO` int DEFAULT NULL COMMENT '등록자 번호',
  `REGIST_DT` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
  `UPDUSR_NO` int DEFAULT NULL COMMENT '수정자 번호',
  `UPDT_DT` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  PRIMARY KEY (`QUESTION_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- planfaidb.tb_question_label definition
CREATE TABLE `tb_question_label` (
  `QUESTION_LABEL_SEQ` int NOT NULL AUTO_INCREMENT,
  `SURVEY_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `SECTION_ID` int NOT NULL,
  `QUESTION_ID` int NOT NULL,
  `QUESTION_LABEL_ID` int NOT NULL,
  `QUESTION_LABEL` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `EXPORTCODE` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `SELECTED` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `REGISTER_NO` int DEFAULT NULL COMMENT '등록자 번호',
  `REGIST_DT` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
  `UPDUSR_NO` int DEFAULT NULL COMMENT '수정자 번호',
  `UPDT_DT` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
  PRIMARY KEY (`QUESTION_LABEL_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;